<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="4246" started-at="2022-06-13T12:54:16 EDT" finished-at="2022-06-13T12:54:20 EDT">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="4246" started-at="2022-06-13T12:54:16 EDT" finished-at="2022-06-13T12:54:20 EDT">
      <class name="com.api.tests.TestGETCustomers">
        <test-method status="PASS" signature="init()[pri:0, instance:com.api.tests.TestGETCustomers@10db82ae]" name="init" is-config="true" duration-ms="954" started-at="2022-06-13T12:54:16 EDT" finished-at="2022-06-13T12:54:17 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="testAllCustomers()[pri:0, instance:com.api.tests.TestGETCustomers@10db82ae]" name="testAllCustomers" duration-ms="1633" started-at="2022-06-13T12:54:17 EDT" finished-at="2022-06-13T12:54:18 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllCustomers -->
        <test-method status="PASS" signature="testParticulerCustomer()[pri:0, instance:com.api.tests.TestGETCustomers@10db82ae]" name="testParticulerCustomer" duration-ms="92" started-at="2022-06-13T12:54:18 EDT" finished-at="2022-06-13T12:54:18 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testParticulerCustomer -->
      </class> <!-- com.api.tests.TestGETCustomers -->
      <class name="com.api.tests.TestPUTCustomer">
        <test-method status="PASS" signature="init()[pri:0, instance:com.api.tests.TestPUTCustomer@6b4a4e18]" name="init" is-config="true" duration-ms="4" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="testUpdateMultipleFields()[pri:0, instance:com.api.tests.TestPUTCustomer@6b4a4e18]" name="testUpdateMultipleFields" duration-ms="82" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateMultipleFields -->
      </class> <!-- com.api.tests.TestPUTCustomer -->
      <class name="com.api.tests.TestPOSTCustomers">
        <test-method status="PASS" signature="init()[pri:0, instance:com.api.tests.TestPOSTCustomers@501edcf1]" name="init" is-config="true" duration-ms="2" started-at="2022-06-13T12:54:18 EDT" finished-at="2022-06-13T12:54:18 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="testPOSTCreateCustomer()[pri:0, instance:com.api.tests.TestPOSTCustomers@501edcf1]" name="testPOSTCreateCustomer" duration-ms="1223" started-at="2022-06-13T12:54:18 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPOSTCreateCustomer -->
      </class> <!-- com.api.tests.TestPOSTCustomers -->
      <class name="com.api.tests.TestDELETECustomer">
        <test-method status="PASS" signature="init()[pri:0, instance:com.api.tests.TestDELETECustomer@78b729e6]" name="init" is-config="true" duration-ms="5" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testDeleteCustomer()[pri:0, instance:com.api.tests.TestDELETECustomer@78b729e6]" name="testDeleteCustomer" duration-ms="73" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.api.helpers.CustomerServiceHelper.deleteCustomer(CustomerServiceHelper.java:118)
at com.api.tests.TestDELETECustomer.testDeleteCustomer(TestDELETECustomer.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteCustomer -->
      </class> <!-- com.api.tests.TestDELETECustomer -->
      <class name="com.api.tests.TestPATCHCustomers">
        <test-method status="PASS" signature="init()[pri:0, instance:com.api.tests.TestPATCHCustomers@27c86f2d]" name="init" is-config="true" duration-ms="3" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testPatchCustomer()[pri:0, instance:com.api.tests.TestPATCHCustomers@27c86f2d]" name="testPatchCustomer" duration-ms="35" started-at="2022-06-13T12:54:20 EDT" finished-at="2022-06-13T12:54:20 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.api.helpers.CustomerServiceHelper.updateCustomerWithSingleField(CustomerServiceHelper.java:106)
at com.api.tests.TestPATCHCustomers.testPatchCustomer(TestPATCHCustomers.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPatchCustomer -->
      </class> <!-- com.api.tests.TestPATCHCustomers -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
